### ISSUE TITLE
Make github releases concurrent with version releases.

### ISSUE THREAD

**Issue by ryanpcmcquen** [alex-97/Thunderpad#1]
I'd really like to package this awesome project for Slackware, but it'd be nice (and a lot more straight-forward) if the latest commit was tagged 0.9.2 (or whatever it is) for the sake of packaging.

Thanks!

**Comment by alex-spataru** [comment]
Hi!
I just created a release for the current commit. However, I marked it as a _pre-release_ because Thunderpad is still lacking some important features (such as selecting the best syntax highlighting definition for the current file) and still has some minor bugs. I will mark it as  _production-ready_ as soon as Thunderpad has better syntax highlighting support and I fix those bugs. I think that everything will be ready in less than a week :)

Greetings!

**Comment by ryanpcmcquen** [comment]
Thanks Alex! That helps a bunch!

Great project and I am glad to be getting in on the ground floor.  ;-)
